apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parking-sys-non-default-namespace
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/mrkhlo/parking-system-infrastructure.git
      path: ./helm/cp-helm-charts
      helm:
        releaseName: kafka
      targetRevision: HEAD
    - repoURL: https://github.com/mrkhlo/parking-system-infrastructure.git
      path: db
      targetRevision: HEAD
    - repoURL: https://github.com/mrkhlo/parking-system-infrastructure.git
      path: kafka-client
      targetRevision: HEAD
    - repoURL: https://github.com/mrkhlo/parking-system-infrastructure.git
      path: app
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: parking-sys

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
